### ISSUE TITLE
Incompatible with Webstorm 2018.1

### ISSUE THREAD

**Issue by ngehlert** [cedricziel/idea-xliff#6]
The plugin looks great, however it looks like it is incompatible with Webstorm 2018.1. I don't find it in the plugins repo and when I try to install it manually I get "Plugin XLIFF Support is incompatible with this installation"

**Comment by cedricziel** [comment]
The XLIFF Support Plugin primarily helps the IDE to associate XML with XLIFF - in its current state, the plugin was broken and I anticipated the version jump on the platform so it's expected behaviour. You can associate the `*.xliff` file type with xml to achieve the very same result.

**Comment by ngehlert** [comment]
oh wow didn't know you can manually associate file types. For anyone finding this thread: Webstorm --> Preferences --> Editor --> File Types
thanks for your quick response @cedricziel . I will close this issue
